apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet-backend-{{ .Values.timestamp | replace ":" "-" | lower }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: faucet-backend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: faucet-backend
  template:
    metadata:
      labels:
        app: faucet-backend
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      containers:
      - name: faucet-backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        env: {{- toYaml .Values.env | nindent 8 }}
        resources:
          requests:
            memory: {{ .Values.deployment.memoryRequest }}
            cpu: {{ .Values.deployment.cpuRequest }}
          limits:
            memory: {{ .Values.deployment.memoryLimit }}
            cpu: {{ .Values.deployment.cpuLimit }}
