apiVersion: v1
kind: Service
metadata:
  name: faucet-backend
  namespace: {{ .Values.service.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: faucet-backend
